# -*- coding: utf-8 -*-
"""Sawit - Palm Tree Counting - Roboflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UoYVF0t5KeJApvown_BHUJwAPmjr694

# Hitung Pohon Sawit Otomatis — Versi Google Colab (tanpa ArcGIS/arcpy)

Ini versi Colab dari notebook aslinya. Karena `arcpy` cuma tersedia di lingkungan ArcGIS Pro (proprietary Esri, tidak bisa diinstal di Colab), semua fungsi baca-raster diganti pakai **rasterio** (open source, sama-sama berbasis GDAL). Output juga diganti dari File Geodatabase (`.gdb`, format khusus Esri) menjadi **GeoPackage (`.gpkg`)** — satu file yang bisa langsung dibuka di ArcGIS Pro maupun QGIS tanpa konversi apa pun.

Tambahan dari versi sebelumnya: sekarang output punya **bounding box**, bukan cuma titik pusat, plus **peta interaktif (HTML)** buat preview cepat hasil deteksi.

Model: **Palm Oil Detection and Counting** (Roboflow Universe, by Prasadnr, `model_id: palm-oil-detection-and-counting/5`).

**Alur kerja:** install & mount Drive → konfigurasi → potong orthomosaic jadi tile & kirim ke Roboflow (titik + bbox) → hapus deteksi ganda di area overlap → simpan sebagai GeoPackage (titik & bbox) → peta interaktif → unduh.

## Langkah 0 — Install library & mount Google Drive
"""

!pip install rasterio geopandas shapely folium rio-cogeo localtileserver --quiet

from google.colab import drive
drive.mount('/content/drive')

"""Setelah Drive ter-mount, upload orthomosaic (`.tif`) kamu ke Google Drive, lalu isi path-nya di Langkah 1 (misalnya `/content/drive/MyDrive/Sawit/Citra_1.tif`).

Kalau filenya kecil dan males mount Drive, bisa pakai `from google.colab import files; files.upload()` — tapi untuk orthomosaic besar, Drive jauh lebih stabil (tidak ada limit ukuran upload widget).

## Langkah 1 — Konfigurasi
"""

ORTHO_RASTER   = "/content/drive/MyDrive/Sawit/Citra_2.tif"          # path orthomosaic di Google Drive
OUTPUT_PATH    = "/content/drive/MyDrive/Sawit/Hasil_Sawit_roboflow.gpkg"     # output GeoPackage, dibuat otomatis
OUTPUT_LAYER   = "deteksi_pohon_sawit"

TILE_SIZE_PX   = 640      # ukuran tile (px), samakan dgn ukuran input model
OVERLAP_PX     = 100      # overlap antar tile (px), agar sawit di tepi tile tak hilang/terpotong
CONF_THRESHOLD = 20       # ambang confidence, 0-100 (naikkan kalau banyak false positive,
                            # turunkan kalau banyak pohon terlewat)
DEDUP_DIST_M   = 3.5      # jarak (meter) minimal antar 2 titik deteksi; kalau lebih dekat
                            # dianggap 1 pohon yg sama. Sesuaikan dgn jarak tanam sawit riil
                            # di lapangan (standar umum segitiga 9x9x9 m -> jarak antar pohon
                            # asli sekitar 8-9,4 m, jadi jangan dekati angka itu)

ROBOFLOW_API_KEY  = "qwerty"   # lihat catatan Colab Secrets di paling bawah
ROBOFLOW_MODEL_ID = "palm-oil-detection-and-counting/5"
API_URL = (
    f"https://detect.roboflow.com/{ROBOFLOW_MODEL_ID}"
    f"?api_key={ROBOFLOW_API_KEY}&confidence={CONF_THRESHOLD}&format=json"
)

"""## Langkah 2 — Fungsi untuk mengirim satu tile ke Roboflow"""

import io, base64, requests
from PIL import Image

def infer_tile(pil_image):
    """Kirim 1 tile (PIL Image) ke Roboflow Hosted API, kembalikan list prediksi
    (tiap prediksi berisi x, y, width, height dalam piksel tile, plus confidence & class)."""
    buffered = io.BytesIO()
    pil_image.save(buffered, quality=90, format="JPEG")
    img_str = base64.b64encode(buffered.getvalue())
    resp = requests.post(
        API_URL,
        data=img_str,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    resp.raise_for_status()
    return resp.json().get("predictions", [])

"""## Langkah 3 — Buka raster, potong jadi tile, & jalankan deteksi (titik + bounding box)

Pakai `rasterio` + `Window` untuk baca raster per-blok langsung dari disk (raster besar tetap aman, tidak dimuat sekaligus ke memori) — prinsipnya sama seperti `RasterToNumPyArray` di versi ArcGIS, hanya beda library.

Roboflow mengembalikan tiap deteksi sebagai titik tengah (`x`, `y`) + ukuran (`width`, `height`) dalam piksel tile. Di sini, selain titik tengah dikonversi ke koordinat peta, 4 sudut bounding box-nya juga ikut dikonversi lewat transform tile yang sama — supaya ukurannya ikut skala asli raster.
"""

import math
import numpy as np
import rasterio
from rasterio.windows import Window, transform as window_transform
from rasterio.transform import xy as pixel_to_map, array_bounds
from PIL import Image

with rasterio.open(ORTHO_RASTER) as src:
    width, height = src.width, src.height
    raster_transform = src.transform
    crs = src.crs
    n_bands = src.count

    print(f"Ukuran raster: {width} x {height} px, {n_bands} band")
    print(f"CRS: {crs} -> "
          f"{'MASIH GEOGRAFIS (derajat), pertimbangkan reproject ke UTM' if crs.is_geographic else 'terproyeksi (OK)'}")

    band_stats = [src.statistics(b, approx=True) for b in range(1, min(n_bands, 3) + 1)]
    global_min = min(s.min for s in band_stats)
    global_max = max(s.max for s in band_stats)
    print(f"Rentang nilai piksel raster (approx): {global_min} - {global_max}")

    step = TILE_SIZE_PX - OVERLAP_PX
    detections = []
    tile_count = 0
    empty_count = 0

    for row0 in range(0, height, step):
        for col0 in range(0, width, step):
            w = min(TILE_SIZE_PX, width - col0)
            h = min(TILE_SIZE_PX, height - row0)
            window = Window(col0, row0, w, h)

            arr = src.read(window=window, masked=True)
            arr = arr.filled(0).astype(np.float64)

            if n_bands >= 3:
                rgb = arr[:3]
            else:
                rgb = np.repeat(arr[:1], 3, axis=0)

            if rgb.max() <= 0:
                empty_count += 1
                continue

            if global_max is not None and global_min is not None and global_max > global_min:
                rgb_norm = np.clip((rgb - global_min) / (global_max - global_min) * 255.0, 0, 255)
            else:
                rgb_norm = rgb

            img_arr = np.moveaxis(rgb_norm, 0, -1).astype("uint8")
            img = Image.fromarray(img_arr)
            preds = infer_tile(img)
            tile_count += 1

            tile_transform = window_transform(window, raster_transform)
            for p in preds:
                map_x, map_y = pixel_to_map(tile_transform, p["y"], p["x"])

                half_w, half_h = p["width"] / 2, p["height"] / 2
                corners_px = [
                    (p["x"] - half_w, p["y"] - half_h),
                    (p["x"] + half_w, p["y"] - half_h),
                    (p["x"] + half_w, p["y"] + half_h),
                    (p["x"] - half_w, p["y"] + half_h),
                ]
                bbox_map = [pixel_to_map(tile_transform, cy, cx) for cx, cy in corners_px]

                detections.append({
                    "x": map_x, "y": map_y,
                    "confidence": p["confidence"], "kelas": p["class"],
                    "bbox": bbox_map,
                })

        print(f"  ...baris {row0}/{height}: {tile_count} tile terkirim, "
              f"{empty_count} tile kosong dilewati, {len(detections)} deteksi")

print(f"Selesai kirim {tile_count} tile ({empty_count} tile kosong dilewati). "
      f"Total deteksi mentah: {len(detections)}")

"""## Langkah 4 — Hapus deteksi ganda (duplikat) di area overlap antar tile

Sama seperti versi ArcGIS: cari titik-titik pusat yang jaraknya lebih dekat dari `DEDUP_DIST_M`, simpan cuma yang confidence-nya tertinggi (bounding box ikut terbawa karena satu paket sama titik pusatnya). Bedanya, konversi ke meter di sini otomatis menyesuaikan CRS raster kamu (geografis vs sudah terproyeksi) — jadi tetap benar walau kamu sudah reproject ke UTM, tidak seperti skrip aslinya yang selalu asumsi derajat.
"""

from scipy.spatial import cKDTree

detections_sorted = sorted(detections, key=lambda d: -d["confidence"])

if crs.is_geographic:
    left, bottom, right, top = array_bounds(height, width, raster_transform)
    mean_lat = (bottom + top) / 2.0
    m_per_deg_lat = 111320.0
    m_per_deg_lon = 111320.0 * math.cos(math.radians(mean_lat))
    coords_m = np.array([
        [(d["x"] - left) * m_per_deg_lon, (d["y"] - bottom) * m_per_deg_lat]
        for d in detections_sorted
    ])
else:
    coords_m = np.array([[d["x"], d["y"]] for d in detections_sorted])

final_detections = []
if len(coords_m) > 0:
    tree = cKDTree(coords_m)
    suppressed = np.zeros(len(detections_sorted), dtype=bool)
    for i, d in enumerate(detections_sorted):
        if suppressed[i]:
            continue
        final_detections.append(d)
        neighbor_idx = tree.query_ball_point(coords_m[i], r=DEDUP_DIST_M)
        for j in neighbor_idx:
            suppressed[j] = True

print(f"Total pohon sawit terhitung (setelah hapus duplikat): {len(final_detections)}")

"""## Langkah 5 — Simpan sebagai GeoPackage (titik + bounding box)

Tidak ada `arcpy`/File Geodatabase di Colab, jadi hasilnya disimpan sebagai **GeoPackage (`.gpkg`)** pakai `geopandas`. Sekarang ada **dua layer** dalam satu file: titik pusat (`deteksi_pohon_sawit`) dan bounding box (`deteksi_pohon_sawit_bbox`) — tinggal pilih mau tampilkan yang mana di ArcGIS Pro/QGIS.
"""

import os
import geopandas as gpd
from shapely.geometry import Point, Polygon

os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

records = [
    {"id_pohon": i, "confidence": d["confidence"], "kelas": d["kelas"]}
    for i, d in enumerate(final_detections, start=1)
]

gdf_points = gpd.GeoDataFrame(records, geometry=[Point(d["x"], d["y"]) for d in final_detections], crs=crs)
gdf_boxes = gpd.GeoDataFrame(records, geometry=[Polygon(d["bbox"]) for d in final_detections], crs=crs)

gdf_points.to_file(OUTPUT_PATH, driver="GPKG", layer=OUTPUT_LAYER)
gdf_boxes.to_file(OUTPUT_PATH, driver="GPKG", layer=f"{OUTPUT_LAYER}_bbox", mode="a")

print(f"Selesai! {len(gdf_points)} titik + {len(gdf_boxes)} bounding box pohon sawit disimpan ke:\n{OUTPUT_PATH}")
gdf_points.head()

"""## Langkah 6 — Peta interaktif (preview raster + titik & bounding box)

Soal usul konversi ke **ECW**: sayangnya nggak bisa dilakukan di Colab. ECW adalah format kompresi milik Hexagon/Erdas yang proprietary — menulis file `.ecw` butuh SDK berbayar yang tidak ada di build GDAL open-source (termasuk yang otomatis ter-install lewat `pip install rasterio`). Jadi, alih-alih convert file, di sini raster dibaca langsung dalam resolusi lebih rendah dari disk (didownsample saat pembacaan, tanpa perlu bikin file baru sama sekali) untuk jadi background peta — hasilnya sama-sama ringan & smooth, tanpa perlu SDK apa pun. Titik dan bounding box pohon lalu di-overlay di atasnya, dan hasil akhirnya adalah file HTML mandiri yang bisa dibuka di browser mana pun atau dikirim ke orang lain.
"""

import numpy as np
from PIL import Image
import folium
from rasterio.enums import Resampling
from rasterio.warp import transform_bounds

PREVIEW_MAX_SIZE = 4000  # naik dari 3000 -> lebih tajam, tapi HTML jadi lebih berat (base64-encoded).
                          # naikkan lagi kalau RAM Colab & ukuran file masih kuat; > ~6000 mulai berat.

with rasterio.open(ORTHO_RASTER) as src:
    scale = min(1.0, PREVIEW_MAX_SIZE / max(src.width, src.height))
    out_w, out_h = max(1, int(src.width * scale)), max(1, int(src.height * scale))
    bands_to_read = min(src.count, 3)

    preview = src.read(out_shape=(bands_to_read, out_h, out_w), resampling=Resampling.average).astype(np.float64)
    if bands_to_read < 3:
        preview = np.repeat(preview[:1], 3, axis=0)

    preview_norm = np.clip((preview - global_min) / (global_max - global_min) * 255.0, 0, 255).astype("uint8")
    preview_img = np.moveaxis(preview_norm, 0, -1)
    west, south, east, north = transform_bounds(src.crs, "EPSG:4326", *src.bounds)

preview_path = "/content/raster_preview_roboflow.png"
Image.fromarray(preview_img).save(preview_path)

center_lat, center_lon = (south + north) / 2, (west + east) / 2

# max_zoom dinaikkan jauh di atas default (~18-19) -> peta gak lagi "mentok"
# zoom_start juga dinaikkan supaya langsung mulai lebih dekat
m = folium.Map(location=[center_lat, center_lon], zoom_start=20, tiles="OpenStreetMap", max_zoom=24)

folium.raster_layers.ImageOverlay(
    image=preview_path, bounds=[[south, west], [north, east]], opacity=0.9, name="Orthomosaic (preview)",
    zindex=1,
).add_to(m)

gdf_boxes_wgs84 = gdf_boxes.to_crs(epsg=4326)
gdf_points_wgs84 = gdf_points.to_crs(epsg=4326)

folium.GeoJson(
    gdf_boxes_wgs84.to_json(), name="Bounding box pohon",
    style_function=lambda f: {"color": "#ff3333", "weight": 1, "fillOpacity": 0.05},
    tooltip=folium.GeoJsonTooltip(fields=["id_pohon", "confidence", "kelas"]),
).add_to(m)

folium.GeoJson(
    gdf_points_wgs84.to_json(), name="Titik pohon",
    marker=folium.CircleMarker(radius=2, color="#33cc33", fill=True, fill_opacity=0.9),
    tooltip=folium.GeoJsonTooltip(fields=["id_pohon", "confidence", "kelas"]),
).add_to(m)

folium.LayerControl().add_to(m)

map_path = os.path.join(os.path.dirname(OUTPUT_PATH), "peta_interaktif_sawit_roboflow.html")
m.save(map_path)
print(f"Peta interaktif disimpan ke: {map_path}")
m

"""Peta di atas cukup dilihat/di-interaksi langsung di sini — tidak perlu (dan tidak bisa) di-`.save()` jadi file portable seperti Opsi A, karena tile-nya bergantung pada server lokal yang cuma hidup selama sesi Colab ini. Kalau mau kirim hasil visual ke orang lain, pakai file HTML.

Kalau mau langsung diunduh ke komputer (bukan cuma tersimpan di Drive):
"""

from google.colab import files

files.download(OUTPUT_PATH)   # GeoPackage (titik + bbox)
files.download(map_path)      # peta portable (Opsi A)

"""## Catatan & tips

- **CONF_THRESHOLD**: naikkan kalau banyak deteksi palsu (*false positive*), turunkan kalau banyak pohon yang terlewat.
- **DEDUP_DIST_M**: sesuaikan dengan jarak tanam sawit riil di lapangan supaya dua pohon yang memang berdekatan tidak keliru dianggap 1 pohon.
- Bounding box dihitung dari `width`/`height` prediksi Roboflow di tiap tile, lalu 4 sudutnya dikonversi ke koordinat peta lewat transform tile masing-masing — jadi ukurannya ikut skala asli raster, bukan ukuran tile 640px.
- Kalau raster kamu masih **geografis (WGS84)**, sebaiknya reproject dulu ke UTM (lewat QGIS, `gdalwarp`, atau `rasterio.warp`) sebelum diproses — hasil hitung jarak & luas jadi lebih akurat. Notebook ini tetap jalan untuk raster geografis (pakai pendekatan konversi derajat->meter), tapi UTM lebih presisi.
- Soal ECW: tidak dipakai karena proprietary (butuh SDK berbayar Hexagon/Erdas, tidak ada di GDAL open-source). Kalau suatu saat butuh format raster ringan buat arsip/serving raster resolusi penuh (bukan cuma preview peta), alternatif open-source yang setara tujuannya adalah **Cloud Optimized GeoTIFF (COG)** — bisa dibuat lewat `gdal_translate -of COG input.tif output_cog.tif`.
- Peta interaktif memakai preview yang di-downsample (maksimal 2000px sisi terpanjang) supaya ringan di browser; cukup untuk overview, bukan untuk analisis piksel presisi.
- Kalau request ke Roboflow gagal terus (timeout dsb): cek dulu kuota API di dashboard Roboflow, atau kemungkinan jaringan kampus/kantor memblokir domain `detect.roboflow.com`.
- API key Roboflow di Langkah 1 tertanam langsung di notebook — kalau notebook ini mau dibagikan ke orang lain/publik, sebaiknya pindahkan ke **Colab Secrets** (ikon kunci di sidebar kiri), lalu panggil dengan:\n`from google.colab import userdata`\n`ROBOFLOW_API_KEY = userdata.get('ROBOFLOW_API_KEY')`

"""